### ISSUE TITLE
红米K50 Android 12 启动时候崩溃

### ISSUE THREAD

**Issue by zhouchengang** [Tile-X/BiCleaner#2]
亲测改成 `icon = application.loadIcon(pm).toBitmap()` 没问题

`2024-09-22 09:18:12.295 21596-21596 AndroidRuntime          cat.app.bicleaner                    E  FATAL EXCEPTION: main
                                                                                                    Process: cat.app.bicleaner, PID: 21596
                                                                                                    java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                                                                                                    	at cat.app.bicleaner.util.PackageUtils$Companion.loadApplicationIcon(PackageUtils.kt:31)
                                                                                                    	at cat.app.bicleaner.data.BilibiliDetail.getBilibiliIcon(BilibiliDetail.kt:19)
                                                                                                    	at cat.app.bicleaner.ui.HomeContentKt.HomeContent(HomeContent.kt:45)
                                                                                                    	at cat.app.bicleaner.ui.BiCleanerAppKt$BiCleanerApp$1$1.invoke(BiCleanerApp.kt:41)
                                                                                                    	at cat.app.bicleaner.ui.BiCleanerAppKt$BiCleanerApp$1$1.invoke(BiCleanerApp.kt:39)`

**Comment by MeowBug** [comment]
好的，收到，最近作者有点忙，后续会修复。
